//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34014
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class SkillInfo
{
	public int skillCode;
	public string name;
	public string prefabName;
	public int attribute;
	public int demage;
	public int numberOfObject;
	public float coolTime;
	public int useLimit;
	public int etc1;
	public int etc2;
	public int etc3;
	public string ICon;

	public SkillInfo ()
	{
		skillCode 		= 0;
		name 			= "";
		prefabName 		= "";
		attribute 		= 0;
		demage 			= 0;
		numberOfObject 	= 0;
		coolTime 		= 0.0f;
		useLimit 		= 0;
		etc1 			= 0;
		etc2 			= 0;
		etc3 			= 0;
		ICon 			= "";
	}

	public SkillInfo (int _skillCode,
	                  string _name,
	                  string _prefabName,
	                  int _attribute,
	                  int _demage,
	                  int _numberOfObject,	 
	                  float _coolTime,
	                  int _useLimit ,
	                  int _etc1 ,
	                  int _etc2 ,
	                  int _etc3,
	                  string _ICon)
	{
		skillCode 		= _skillCode;
		name 			= _name;
		prefabName 		= _prefabName;
		attribute 		= _attribute;
		demage 			= _demage;
		numberOfObject 	= _numberOfObject;	
		coolTime 		= _coolTime;	
		useLimit 		= _useLimit;
		etc1 			= _etc1;
		etc2			= _etc2;
		etc3			= _etc3;
		ICon 			= _ICon;
	}

	public override string ToString()
	{

		string A = "";

		A += skillCode.ToString () + " " + name.ToString () +" ";
		A += prefabName.ToString () + " " + attribute.ToString () +" ";
		A += demage.ToString () + " " + numberOfObject.ToString () +" ";
		A += coolTime.ToString () + " " + useLimit.ToString() +" ";
		A += ICon;

		return A;
	}


}

